#!/bin/csh
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org)

# This folder contains a pre-optimized PDB structure and OpenMM inputs.
# All input files were optimized for OpenMM v6.2 or above, so lower version of OpenMM can cause some errors.
# You can get the latest development version of OpenMM at the git repository:
# https://github.com/pandegroup/openmm


# Equilibration
# step6.[1-6]

set init = step5_charmm2omm
set cnt = 1

while ( ${cnt} <= 6 )
    @ pcnt = ${cnt} - 1
    set istep = step6.${cnt}_equilibration
    set pstep = step6.${pcnt}_equilibration

    if ( ${cnt} == 1 ) then
        python -u openmm_run.py -i ${istep}.inp -t toppar.str -p ${init}.psf -c ${init}.crd -b ${init}.str -orst ${istep}.rst -odcd ${istep}.dcd > ${istep}.out
    else
        python -u openmm_run.py -i ${istep}.inp -t toppar.str -p ${init}.psf -c ${init}.crd -irst ${pstep}.rst -orst ${istep}.rst -odcd ${istep}.dcd > ${istep}.out
    endif
    @ cnt += 1
end


# Production

# The OpenMM check point file (.chk) cannot be used in a different machine environment.
# So please make sure if you are using the same GPU and CUDA version of machine while doing additional
# production steps with the check point file.

set cnt = 1
set cntmax = 10

set input = step7_production

while ( ${cnt} <= ${cntmax} )
    @ pcnt = ${cnt} - 1
    set istep = step7_${cnt}
    set pstep = step7_${pcnt}

    if ( ${cnt} == 1 ) set pstep = step6.6_equilibration

    python -u openmm_run.py -i ${input}.inp -t toppar.str -p ${init}.psf -c ${init}.crd -irst ${pstep}.rst -orst ${istep}.rst -odcd ${istep}.dcd > ${istep}.out
    @ cnt += 1
end

